<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks Condition="'$(IsWindows)'">net461;netstandard2.1</TargetFrameworks>
    <TargetFrameworks Condition="'$(IsWindows)' == 'false'">netstandard2.1</TargetFrameworks>
    <LangVersion>8.0</LangVersion>
    <OutputPath>bin\$(Configuration)\$(TargetFramework)\lordmilko.BuildTools\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)\$(Configuration)\$(TargetFramework.ToLowerInvariant())\</IntermediateOutputPath>

    <TestAdapterPath>..\PowerShell.TestAdapter\bin\$(Configuration)\netstandard2.0\PowerShell.TestAdapter.dll</TestAdapterPath>
  </PropertyGroup>

  <ItemGroup Condition="'$(FrameworkType)' == 'Full'">
    <PackageReference Include="Microsoft.PowerShell.5.ReferenceAssemblies" Version="1.1.0" PrivateAssets="all" />
    <PackageReference Include="System.IO.Compression" Version="4.3.0" PrivateAssets="all" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup Condition="'$(FrameworkType)' != 'Full'">
    <PackageReference Include="PowerShellStandard.Library" Version="5.1.1" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Update="BuildTools.Format.ps1xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="lordmilko.BuildTools.psd1">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="ClearReferenceCopyLocalPaths" AfterTargets="ResolveReferences">
    <ItemGroup>
      <ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)" Condition="'%(ReferenceCopyLocalPaths.NuGetPackageId)' == 'Microsoft.PowerShell.5.ReferenceAssemblies' OR '%(ReferenceCopyLocalPaths.NuGetPackageId)' == 'System.IO.Compression'" />
    </ItemGroup>
  </Target>

  <Target Name="CopyTestAdapter" AfterTargets="Build">

    <Error Condition="!Exists('$(TestAdapterPath)')" Text="'$(TestAdapterPath)' does not exist" />
    
    <!-- For some reason this gets called 3 times; one of the times the TargetFramework is empty, so we need to exclude it -->
    <Copy SourceFiles="$(TestAdapterPath)" DestinationFolder="$(OutputPath)\TestAdapters" Condition="'$(TargetFramework)' != ''" />
  </Target>

</Project>
